### PR TITLE
Upstream all changes

### PR DESCRIPTION
**Pull request by paulirish**
Bringing up the work from @JamesHagerman  in https://github.com/paulirish/muse-node/pull/1 along with some other changes.

### CODE REVIEW

**Comment by JamesHagerman** [comment]
Hey @bobi-rakova! Is it possible for you to accept this pull request?

**Comment by bobi-rakova** [comment]
Guys this is awesome! I've been thinking about a side project idea related to EEG and chatbots. Maybe you'll be interested to play around with this? @JamesHagerman @paulirish

**Comment by paulirish** [comment]
Beautiful. Thanks @JamesHagerman for making this repo convergence happen. :)

**Comment by JamesHagerman** [comment]
Absolutely! I've got too much on my plate right now to dig into this more but I'm excited to get to it asap!

Thank you both!

**Pull request merged**
